OhSnip/Models/Snippet.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace OhSnip.Models
{
    public class Snippet : BaseEntity
    {
        public int SnippetId { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string Language { get; set; }
        public string Code { get; set; }
        public string Link { get; set; }
        public string ApplicationUserId { get; set; }
        public ApplicationUser User { get; set; }
    }
}

OhSnip/Models/SnippetViewModels/DashboardViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace OhSnip.Models.SnippetViewModels
{
    public class DashboardViewModel
    {
        public List<Snippet> Snippets { get; set; }

        public DashboardViewModel()
        {
            Snippets = new List<Snippet>();
        }
    }
}

OhSnip/Controllers/SnippetController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Authentication;

using OhSnip.Models.SnippetViewModels;
using OhSnip.Models;
using OhSnip.Data;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace OhSnip.Controllers
{
    public class SnippetController : Controller
    {
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly OhSnipContext _context;

        public SnippetController(OhSnipContext context, UserManager<ApplicationUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        [Route("Dashboard")]
        public async Task<IActionResult> Dashboard()
        {
            var user = await _userManager.GetUserAsync(User);
            if (user == null)
            {
                TempData["ErrorMessage"] = "You must login before viewing that page!";
                return RedirectToAction("Login", "Account");
            }

            List<Snippet> allsnippets = _context
                .Snippets
                .Where(item => user.Id == item.ApplicationUserId)
                .ToList();
            DashboardViewModel displaySnippets = new DashboardViewModel()
            {
                Snippets = allsnippets
            };

            return View(displaySnippets);
        }

        [HttpGet]
        [Route("AddSnippet")]
        public async Task<IActionResult> ShowAddSnippet()
        {
            var user = await _userManager.GetUserAsync(User);
            if (user == null)
            {
                TempData["ErrorMessage"] = "You must login before viewing that page!";
                return RedirectToAction("Login", "Account");
            }

            DetailViewModel model = new DetailViewModel();
            return View("AddSnippet", model);
        }
        [HttpPost]
        [Route("Create")]
        public async Task<IActionResult> Create(DetailViewModel snip)
        {
            var user = await _userManager.GetUserAsync(User);

            if (ModelState.IsValid)
            {
                Snippet newSnip = new Snippet
                {
                    Title = snip.Title,
                    Description = snip.Description,
                    Language = snip.Language,
                    Code = snip.Code,
                    Link = snip.Link,
                    ApplicationUserId = user.Id,
                };
                _context.Snippets.Add(newSnip);
                _context.SaveChanges();
                return RedirectToAction("Dashboard");

            }
            return View("AddSnippet", snip);
        }         

    [HttpGet]
        [Route("EditSnippet/{id}")]
        public async Task<IActionResult> ShowEditSnippet(int id)
        {
            var user = await _userManager.GetUserAsync(User);
            if (user == null)
            {
                TempData["ErrorMessage"] = "You must login before viewing that page!";
                return RedirectToAction("Login", "Account");
            }

            DetailViewModel model = new DetailViewModel();
            ViewBag.snippettoedit = _context.Snippets.Where(snip => snip.SnippetId == id);
            return View("EditSnippet", model);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(DetailViewModel snip, int id)
        {
            if (ModelState.IsValid)
            {
                var sniptoupdate = await _context.Snippets.FirstOrDefaultAsync(s => s.SnippetId == id);
                sniptoupdate.Title = snip.Title;
                sniptoupdate.Description = snip.Description;
                sniptoupdate.Language = snip.Language;
                sniptoupdate.Code = snip.Code;
                sniptoupdate.Link = snip.Link;
                _context.Snippets.Update(sniptoupdate);
                await _context.SaveChangesAsync();

                return RedirectToAction(nameof(Dashboard));
            }
            return View(snip);
        }

        [HttpGet]
        [Route("DeleteSnippet/{id}")]
        public async Task<IActionResult> DeleteSnippet(int id)
        {
            var user = await _userManager.GetUserAsync(User);
            if (user == null)
            {
                TempData["ErrorMessage"] = "You must login before viewing that page!";
                return RedirectToAction("Login", "Account");
            }

            ViewBag.sniptodelete = _context.Snippets.Where(snip => snip.SnippetId == id);
            return View();
        }

        [HttpGet]
        [Route("Delete/{id}")]
        public IActionResult Delete(int id)
        {
            Snippet snipdelete = _context.Snippets.Where(snip => snip.SnippetId == id).SingleOrDefault();
            _context.Snippets.Remove(snipdelete);
            _context.SaveChanges();
            return RedirectToAction("Dashboard");

        }

        [HttpPost]
        [Route("Search")]
        public async Task<IActionResult> Search(string searchString)
        {
            var user = await _userManager.GetUserAsync(User);
            DashboardViewModel searchSnippets = new DashboardViewModel()
            {
            Snippets = _context
                .Snippets
                .Where(item => item.Code.Contains(searchString)
                    || item.Description.Contains(searchString)
                    || item.Title.Contains(searchString)
                    )
                .Where(item => user.Id == item.ApplicationUserId)
                .ToList()
            };
            return View("Dashboard", searchSnippets);
        }
        


        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

    }
}

OhSnip/Views/Snippet/AddSnippet.cshtml
@model OhSnip.Models.SnippetViewModels.DetailViewModel

@{
    ViewData["Title"] = "Add Snippet";
}

<h2>Add Snippet</h2>

<form asp-controller="Snippet" asp-action="Create" method="post" class="col-xs-4">
    <div class="form-group">
        <label asp-for="Title">Title</label>
        <input asp-for="Title" class="form-control" />
        <span asp-validation-for="Title" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Description">Description</label>
        <input asp-for="Description" class="form-control" />
        <span asp-validation-for="Description" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Language">Language</label>
        <select asp-for="Language" asp-items="Model.Languages" class="form-control"></select>
        <span asp-validation-for="Language" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Code">Code</label>
        <textarea asp-for="Code" class="form-control" placeholder="Add new code or snippet here."></textarea>
        <span asp-validation-for="Code" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Link">Source</label>
        <input asp-for="Link" class="form-control" />
        <span asp-validation-for="Link" class="text-danger"></span>
    </div>
    <div class="form-group">
        <button type="submit" class="btn btn-default">Add</button>
    </div>
</form>

OhSnip/Views/Snippet/Dashboard.cshtml
@using Microsoft.AspNetCore.Identity
@using OhSnip.Models

@model OhSnip.Models.SnippetViewModels.DashboardViewModel

@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager

@{
    ViewData["Title"] = "Dashboard";
}

<script>
    /* Set the width of the side navigation to 250px and the left margin of the page content to 250px */
    function openNav() {
        document.getElementById("mySidenav").style.width = "250px";
        document.getElementById("main").style.marginLeft = "250px";
        document.getElementById("openButton").style.visibility = "hidden";
    }

    /* Set the width of the side navigation to 0 and the left margin of the page content to 0 */
    function closeNav() {
        document.getElementById("mySidenav").style.width = "0";
        document.getElementById("main").style.marginLeft = "0";
        document.getElementById("openButton").style.visibility = "visible";
    }
</script>


<nav id="mySidenav" class="sidenav">
    <a href="#" class="closebtn" onclick="closeNav()">&times;</a>
    <a href="#" id="allSnippets">All Snippets</a>
    <a href="#" class="language" name="C">C</a>
    <a href="#" class="language" name="C\#">C#</a>
    <a href="#" class="language" name="C++">C++</a>
    <a href="#" class="language" name="CSS">CSS</a>
    <a href="#" class="language" name="Haskell">Haskell</a>
    <a href="#" class="language" name="HTML">HTML</a>
    <a href="#" class="language" name="Java">Java</a>
    <a href="#" class="language" name="JavaScript">JavaScript</a>
    <a href="#" class="language" name="JavaScript React">JavaScript React</a>
    <a href="#" class="language" name="JSON">JSON</a>
    <a href="#" class="language" name="Markdown">Markdown</a>
    <a href="#" class="language" name="PHP">PHP</a>
    <a href="#" class="language" name="Plain Text">Plain Text</a>
    <a href="#" class="language" name="Python">Python</a>
    <a href="#" class="language" name="R">R</a>
    <a href="#" class="language" name="Razor">Razor</a>
    <a href="#" class="language" name="Ruby">Ruby</a>
    <a href="#" class="language" name="SQL">SQL</a>
    <a href="#" class="language" name="Swift">Swift</a>
    <a href="#" class="language" name="Typescript">Typescript</a>
    <a href="#" class="language" name="Visual Basic">Visual Basic</a>
    <a href="#" class="language" name="XML">XML</a>
</nav>

<div id="main" class="main">
    <span id="openButton" onclick="openNav()"><span class="glyphicon glyphicon-chevron-left"></span> sort by language</span>

    <p><a class="button" type="button" href="/AddSnippet">New Snippet</a></p>

    <form asp-controller="Snippet" asp-action="Search" method="post">
        <div class="input-group col-xs-12 col-md-6">
            <input type="text" class="form-control" name="searchString" placeholder="Search" />
            <div class="input-group-btn">
                <button type="submit" class="btn btn-default">
                    <i class="glyphicon glyphicon-search"></i> 
                </button>
            </div>
        </div>
    </form>


    @foreach (var snip in Model.Snippets)
    {
        <div class="snippet @snip.Language">
            <h3 class="clicker">@snip.Title</h3>
            <p>@snip.Description</p>
            <div class="hidetoggle">
                <a title="Copy" class="btn masterTooltip" data-clipboard-text="@snip.Code">
                    <span class="glyphicon glyphicon-duplicate"></span>
                </a>
                <p class="code">@snip.Code</p>
                <p><a href="@snip.Link">@snip.Link</a></p>
                <a class="button" type="button" href="/EditSnippet/@snip.SnippetId">Edit</a>
                <a type="button" class="button" href="/DeleteSnippet/@snip.SnippetId">Delete</a>
            </div>
        </div>
    }
</div>
<script>
    $("div.hidetoggle").hide();
    $('h3.clicker').each(function () {
        $(this).click(function () {
            $(this).siblings('div.hidetoggle').toggle("slow");
        });
    });
    $('.language').click(function () {
        var lang = $(this).attr("name");
        $('.snippet').hide();
        $('.' + lang).show();
    });
    $('#allSnippets').click(function () {
        $('.snippet').show();
        $('.masterTooltip').hover(function () {
            // Hover over code
            var title = $(this).attr('title');
            $(this).data('tipText', title).removeAttr('title');
            $('<p class="tooltip"></p>')
                .text(title)
                .appendTo('body')
                .show('fast');
        }, function () {
            // Hover out code
            $(this).attr('title', $(this).data('tipText'));
            $('.tooltip').remove();
        });
    });

</script>

OhSnip/Views/Snippet/DeleteSnippet.cshtml
@model OhSnip.Models.SnippetViewModels.DetailViewModel

@{
    ViewData["Title"] = "Delete Snippet";
}

<h2>Delete Snippet</h2>

@foreach (var snip in @ViewBag.sniptodelete)
{
    <p>"@snip.Title"</p>
    <p>"@snip.Description"</p>
    <p>"@snip.Code"</p>
    <p>@snip.SnippetId</p>
    <a href="/Delete/@snip.SnippetId">Delete</a>
}

OhSnip/Views/Snippet/EditSnippet.cshtml
@model OhSnip.Models.SnippetViewModels.DetailViewModel

@{
    ViewData["Title"] = "Edit Snippet";
}

<h2>Edit Snippet</h2>

@foreach (var snip in @ViewBag.snippettoedit)
{
    <form asp-controller="Snippet" asp-action="Edit/@snip.SnippetId" method="post" class="col-xs-4">
        <div class="form-group">
            <label asp-for="Title">Title</label>
            <input asp-for="Title" value="@snip.Title" class="form-control" />
            <span asp-validation-for="Title" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="Description">Description</label>
            <input asp-for="Description" value="@snip.Description" class="form-control" />
            <span asp-validation-for="Description" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="Language">Language</label>
            <select asp-for="Language" asp-items="Model.Languages" class="form-control"></select>
            <span asp-validation-for="Language" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="Code">Code</label>
            <textarea name="Code" class="form-control">@snip.Code</textarea>
            <span asp-validation-for="Code" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="Link">Source</label>
            <input asp-for="Link" value="@snip.Link" class="form-control" />
            <span asp-validation-for="Link" class="text-danger"></span>
        </div>
        <input type="hidden" name="SnippetId" value="@snip.SnippetId" />
        <div class="form-group">
            <button type="submit" class="btn btn-default">Update</button>
        </div>
    </form>
}

OhSnip/Views/Snippet/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<h2>Welcome to OhSnip</h2>